export const IPC_CHANNELS = {
  SETTINGS_GET: 'settings:get',
  SETTINGS_UPDATE: 'settings:update',
  SETTINGS_DISCOVER_MODELS: 'settings:discover-models',
  SETTINGS_SELECT_WORKSPACE: 'settings:select-workspace',
  PERMISSION_GRANT_DELETE: 'permission-grant:delete',
  WINDOW_GET_POSITION: 'window:get-position',
  WINDOW_SET_POSITION: 'window:set-position',
  AGENT_BACKEND_GET_STATUS: 'agent-backend:get-status',
  AGENT_BACKEND_STATUS: 'agent-backend:status',
  AGENT_RUN_LIST: 'agent-run:list',
  AGENT_EXECUTION_RECORD_LIST: 'agent-execution-record:list',
  ARTIFACT_LIST: 'artifact:list',
  ARTIFACT_APPLY: 'artifact:apply',
  ARTIFACT_EXPORT: 'artifact:export',
  CONTEXT_ATTACHMENT_STAGE: 'context-attachment:stage',
  CONTEXT_ATTACHMENT_REMOVE: 'context-attachment:remove',
} as const
