export const IPC_CHANNELS = {
  SETTINGS_GET: 'settings:get',
  WINDOW_GET_POSITION: 'window:get-position',
  WINDOW_SET_POSITION: 'window:set-position',
  ASSISTANT_STREAM: 'assistant:stream',
  APPROVAL_REQUEST: 'approval:request',
  APPROVAL_RESPOND: 'approval:respond',
  AGENT_SESSION_CREATE: 'agent-session:create',
  AGENT_SESSION_LIST: 'agent-session:list',
  AGENT_SESSION_RENAME: 'agent-session:rename',
  AGENT_SESSION_DELETE: 'agent-session:delete',
  AGENT_RUN_LIST: 'agent-run:list',
  AGENT_MESSAGE_LIST: 'agent-message:list',
  AGENT_MESSAGE_SAVE: 'agent-message:save',
} as const
