export const IPC_CHANNELS = {
  SETTINGS_GET: 'settings:get',
  SETTINGS_UPDATE: 'settings:update',
  SETTINGS_SELECT_WORKSPACE: 'settings:select-workspace',
  PERMISSION_GRANT_DELETE: 'permission-grant:delete',
  WINDOW_GET_POSITION: 'window:get-position',
  WINDOW_SET_POSITION: 'window:set-position',
  PI_THREAD_LIST: 'pi:thread:list',
  PI_THREAD_CREATE: 'pi:thread:create',
  PI_THREAD_GET: 'pi:thread:get',
  PI_THREAD_RENAME: 'pi:thread:rename',
  PI_THREAD_ARCHIVE: 'pi:thread:archive',
  PI_THREAD_UNARCHIVE: 'pi:thread:unarchive',
  PI_THREAD_DELETE: 'pi:thread:delete',
  PI_THREAD_SUBSCRIBE: 'pi:thread:subscribe',
  PI_MESSAGE_SEND: 'pi:message:send',
  PI_RUN_CANCEL: 'pi:run:cancel',
  PI_QUEUE_CLEAR: 'pi:queue:clear',
  PI_MODEL_LIST: 'pi:model:list',
  PI_MODEL_SET: 'pi:model:set',
  PI_THINKING_SET: 'pi:thinking:set',
  PI_HOST_UI_RESPOND: 'pi:host-ui:respond',
  AGENT_RUN_LIST: 'agent-run:list',
  AGENT_EXECUTION_RECORD_LIST: 'agent-execution-record:list',
  ARTIFACT_LIST: 'artifact:list',
  ARTIFACT_APPLY: 'artifact:apply',
  ARTIFACT_EXPORT: 'artifact:export',
} as const
